# Generated by Django 5.2.4 on 2025-07-15 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='timezones',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
